import os;
#env = Environment();
env = Environment();

env.Replace(CC='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang')
env.Replace(CXX='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++')
env.Replace(CC='xcrun clang')
env.Replace(CXX='xcrun clang++')
env.Append(CXXFLAGS=['-std=c++11', '-stdlib=libc++', '-g', '-O0', '-Wall'])
#env.Append(CXXFLAGS=['-std=c++11', '-stdlib=libc++', '-O3', '-Wall'])
env.Append(LINKFLAGS=['-std=c++11', '-stdlib=libc++']);


#Print the environment
#print os.environ;
#dict = env.Dictionary()
#for key in ['CC', 'CXX', 'CFLAGS', 'CXXFLAGS']:
#	print "%s = %s" % (key, dict[key])

env.Program(target = 'kompute', source = ["cxx/entry.cpp", "cxx/stack.cpp", "cxx/koroutine.cpp", "cxx/koro.cpp", "cxx/kompute.cpp", "cxx/komp.cpp", "cxx/tutil.cpp"])

