#if !defined (PARSER_CALLBACK_HPP_)
#define PARSER_CALLBACK_HPP_

#include "ScannerCallback.hpp"
#include "parser.hpp"
#include "scanner.hpp"


namespace komp {
	class ParserCallback {
	public:
		using Node = komp::grammar::Node;
		ParserCallback();
		~ParserCallback();
		int lex(YYSTYPE *, YYLTYPE *);
	private:
		yyscan_t scanner;
		ScannerCallback scannerCallback;
	};
	
	//This is called by komp_ParserCallback_parse to pull tokens. We need to return the integer token
	int komp_ParserCallback_lex(YYSTYPE *, YYLTYPE *, ParserCallback *);
	
	//This is called by komp_ParserCallback_parse to notify us of an error
	void komp_ParserCallback_error(YYLTYPE *, komp::ParserCallback * parserCallback, const char * errorString);
}

//This is implemented by the file generated by bison. We call it to perform the parse
int komp_ParserCallback_parse(komp::ParserCallback *);

#endif
